default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bank_dev

test:
  <<: *default
  database: bank_test

production:
  <<: *default
  database: bank_prod
